### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by KatKeeeen** [KatKeeeen/protospace-38577#1]
https://protospace-38577.onrender.com

**Comment by snkw-works** [comment]
@KatKeeeen さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**
**ユーザー詳細機能**
- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されるよう修正しましょう**
「ユーザー名さんの情報」・「ユーザー名さんのプロトタイプ」の「ユーザー名」となっているところは、該当するユーザーの名前が入るようにしましょう。
<img width="655" alt="スクリーンショット 2023-01-04 10 08 23" src="https://user-images.githubusercontent.com/54050089/210674298-02271697-43be-4749-b546-50a33f2b2d26.png">

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
挙動確認を行い、修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by KatKeeeen** [comment]
ご確認頂きありがとうございます。
上記、修正を致しましたので、再度ご確認いただけますと幸いです。
よろしくお願い致します。

**Comment by maru2628** [comment]
@KatKeeeen さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
